repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v3.4.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
          - id: check-added-large-files
    - repo: https://github.com/prettier/prettier
      rev: 2.3.2
      hooks:
          - id: prettier
            files: \.js$
            additional_dependencies: ["prettier"]
            language: node
    - repo: https://github.com/conventional-changelog/commitlint
      rev: v13.1.0
      hooks:
          - id: commitlint
            stages: [commit-msg]
