version: "3"
services:
    app:
        build: .
        ports:
            - "4000:4000"
        depends_on:
            - mongo
    mongo:
        image: "mongo:latest"
        ports:
            - "27017:27017"
